### ISSUE TITLE
Warn on $ref with ignored sibling properties

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#134]
From [ZEN-2696](https://modelsolv.atlassian.net/browse/ZEN-2696):
The Uber Swagger examples (both single- and multi-file versions) contain the following erroneous Swagger:

```
Activities:
    properties:
      offset:
        type: integer
        format: int32
        description: Position in pagination.
      limit:
        type: integer
        format: int32
        description: Number of items to retrieve (100 max).
      count:
        type: integer
        format: int32
        description: Total number of items available.
      history:
        type: array
        $ref: Activity
```

The `history` property is supposed to be an array of `Activity` objects, but in fact it's just a single `Activity` object. It's missing the `items` property.

It is not erroneous for a JSON Ref node to contain properties other than `$ref`, but all such properties are ignored according to the spec. This may be a condition that merits a warning in SwagEdit to help prevent this sort of error.
