### ISSUE TITLE
Local Reference to Tags Doesn't Validate

### ISSUE THREAD

**Issue by pixelshaded** [RepreZen/KaiZen-OpenAPI-Editor#163]
Spec

``` yaml
swagger: '2.0'
info:
  version: "0.0.0"
  title: Settings UI API
  description: Api for the UI of settings.ignitionone.com
basePath: /api
tags:
  $ref: 'settingsUI/tags.yaml'
```

Tags

``` yaml
-
  name: User
  description: User Endpoints
-
  name: RateCard
  description: Rate Card Endpoints
-
  name: Role
  description: Role Endpoints
```

Hovering over the x, the message says:

```
value of type object is not allowed, value should be of type array
```

I've used this spec in swagger-editor so as long as the files are linked properly (seems to be since I can ctrl click the path and go to the file), this should work.
