### ISSUE TITLE
Validation should require YAML keys to be scalar strings

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#253]
Dicussion in [ZEN-3175](https://modelsolv.atlassian.net/browse/ZEN-3175) reveals that SwagEdit is extremely tolerant of YAML keys (at least in some cases) that are not valid strings.

A Swagger spec with this `definitions` section produces no errors or warnings from SwagEdit:

```
definitions:
  null:
    type: string
  'null':
    type: string
  true :
    type: string
  350 :
    type: integer
  [1, 2, 3]:
    type: string
  {"foo" : "bar", "ping" : "pong"}:
    type: number
  {"YAML Set", "Not even legal JSON", "AFAIK"}:
    type: string
    
  TaxFilingObject:
    type: object
    properties:
      null:
        type: string
      'null':
        type: string
      true :
        type: string
      350 :
        type: integer
      [1, 2, 3]:
        type: string
      {"foo" : "bar", "ping" : "pong"}:
        type: number
      {"YAML Set", "Not even legal JSON", "AFAIK"}:
        type: string
 ```

This is valid YAML.  YAML mappings allow non-string scalar keys, and even non-scalar keys.  But it should not be valid Swagger, or even valid "YAML-as-JSON".

The [OpenAPI 2.0 spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) does not specify which version of YAML it uses, and this may be significant because the current release of SnakeYAML is v1.1 compliant, while the most recent YAML spec is 1.2.

It also does not specify which YAML Schema should be used to interpret OpenAPI specs.

**TERMINOLOGY NOTE** - A [YAML schema](http://www.yaml.org/spec/1.2/spec.html#Schema) is not the same kind of animal as a JSON Schema.  YAML uses optional [tags](http://www.yaml.org/spec/1.2/spec.html#tag//) to ascribe data types to values. A YAML schema is a combination of a set of tags and a mechanism for ascribing types to values that are untagged, or have non-specific tags.  Confusingly, YAML uses the term "[JSON Schema](http://www.yaml.org/spec/1.2/spec.html#id2803231)" to refer to one of its recommended YAML schemas.  YAML's JSON Schema is used to interpret YAML as JSON.  It is _not the same thing_ as the JSON Schema language defined at [json-schema.org](json-schema.org) and used as the basis of OpenAPI's schema object.

In spite of these omissions, the JSON Spec is clear that keys must be strings. 

A search through the OpenAPI spec for "Field Pattern" shows that Swagger uses `{name}` as a field pattern for schema objects in the definitions section, and several other places.  It doesn't specify what constitutes a legal `{name}`, and it defers to JSON Schema as to the format of keys in the `properties` section, but presumably these are also `{name}`s.  

Note that the [Responses Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#user-content-patterned-fields-3) has an `{HTTP Status Code}` field pattern. Of course these are numeric, and though the spec examples show them with quotes, it's very common to see them in YAML without quotes.  So we shouldn't flag non-string scalar keys as errors or even warnings, at least not in all cases.

I recommend the following changes:
* Disallow any non-scalar property key.  This is clearly a requirement for JSON compatibility. It does not need to be configurable.  Error message can be "Keys must be scalar string values."
* Wherever the OpenAPI Specification uses `{name}` as a field pattern, detect and mark any cases where the key would be interpreted as something other than a scalar string, according to the [tag resolution rules](http://www.yaml.org/spec/1.2/spec.html#id2804356) for YAML's JSON Schema.  
    * The text can be "Keys in this object should be strings. The specified key may be interpreted as a boolean, null, or number value. You can enclose the key in single or double quotes to ensure correct interpretation as a string."
    * The severity can be configurable as error, warning, or ignore.  Warning should be the default. 
* Apply the same `{name}` treatment to property names within a schema, recursively.  This may not be comprehensive, as there may be other keys within a schema that must also be strings; but this is a good start.

**Comment by tedepstein** [comment]
Observations, after further experimentation with property names in the definitions section:

* Properties with non-string scalar keys are tolerated by SwagEdit without any warning or error. 

```
definitions:
  Pet:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      538:
        type: string
      true :
        type: string
```

* A non-scalar key in an otherwise normal Swagger file, with no other unusual keys, will show as a somewhat misleading validation error on the containing schema. In the following example, the error is reported on `Pet` as "Invalid type definition, object has a required field but is missing a properties field."  This only happens if the `required` property is present; if I remove it, the error goes away.

```
definitions:
  Pet:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      ["zap", "zotz"] :
        type: string
```

* Adding a null key property to the above example seems to short-circuit the validation.  It no longer displays an error.  So in fact the presence of `null` as a key (or possibly other unusual keys) can mask validation altogether.  This same effect is observable even if the `null` key occurs in another object, before or after the one with the non-scalar key.

```
  Pet:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      ["zap", "zotz"] :
        type: string
      null:
        type: string
```
