### ISSUE TITLE
Issues with Content-assist

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#30]
## Content-assist for patternProperties

Invoke content-assist for response code:
<img width="380" alt="screen shot 2016-01-27 at 5 29 02 pm" src="https://cloud.githubusercontent.com/assets/644582/12630671/86491238-c51b-11e5-991a-aaa761c9f4f2.png">

The first option is `([0-9]{3})$|^(default)$`, choosing it will create an invalid model:

``` yaml
  /taxFilings:
    get:
      responses:
        ([0-9]{3})$|^(default)$:
```

PatternProperties probably are probably more useful in proposal description than for replacementString.

**Comment by tfesenko** [comment]
## `path` value for method parameters `in`

Line 26 of the default model defines the `"path"` value. However, content-assist does not provide it.

``` yaml
        in: "path"
```

**Comment by tfesenko** [comment]
## "$ref" key not provided by content-assist

UPD: now it works

Line 34 of default model:

``` yaml
          schema:
            $ref: "#/definitions/TaxFilingObject"
```

**Comment by tfesenko** [comment]
## `type` keyword in definitons and properties

There is no code assist for type value of definition or property, e.g. 

``` yaml
definitions:
  TaxFilingObject:
    type: "object"
```

and (for `filingID`)

``` yaml
  TaxFilingObject:
    type: "object"
    description: "An individual Tax Filing record, accessed by its ID"
    properties:
      filingID:
        type: "string"
```

Parameters type works fine.
