### ISSUE TITLE
OpenApi v3: Code assist for Link#operationRef

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#305]
Extracted from #289 
[Link#operationRef](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#link-object) is
> a relative or absolute reference to an OAS operation. This field is mutually exclusive with the operationId field, and must point to the fragment of a valid OAS definition.

For now, only show a relative operationRef:
```yaml
components:
  links:
    UserRepositories:
      # returns array of '#/components/schemas/repository'
      operationRef: '#paths~12.0~1repositories~1{$response.body#/username}'
```

**Comment by ghillairet** [comment]
If I take the default example, is this a valid operationRef?

```yaml
components:
  links:
    UserCommitHistory:
      operationId: listPets
      operationRef: "#/paths/~1pets/get/"
```
