### ISSUE TITLE
Add navigation for security requirement scopes

### ISSUE THREAD

**Issue by ghillairet** [RepreZen/KaiZen-OpenAPI-Editor#407]
In case the security scheme is oauth or openIdConnect, it should be doable to provide navigation to the named scopes.

For ex, clicking on `write:pets`

```yaml
petstore_auth:
- write:pets
- read:pets
```

would move the cursor to the scope write:pets in /definitions/securitySchemes:

```yaml
type: oauth2
flows: 
  implicit:
    authorizationUrl: https://example.com/api/oauth/dialog
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets
```

Related to #335
