### ISSUE TITLE
Query parameter template includes default type integer/format int64

### ISSUE THREAD

**Issue by jfiala** [RepreZen/KaiZen-OpenAPI-Editor#421]
It would be better to have a more generic query parameter template (without the type) and then maybe offer types for integer/string etc. additionally?
Currently each query parameter <> integer would have to be corrected (or add custom templates).

**Comment by tfesenko** [comment]
## OpenAPI v3
I do see an `int64` type in the OAS3 header parameter template:
```yaml
name: ${name}
in: header
description: ${ID}
required: true
schema:
  type: array
  items:
    type: ${integer}
    format: int64
style: commaDelimited
```
## Swagger v2
We also use the `int64` in the path, header, query, and form data parameter templates for Swagger v2.

This change is easy and I think it makes sense. 
@tedepstein , should we add this issue to the current sprint?
