### ISSUE TITLE
Wrong error issued with OpenID Connect security schema

### ISSUE THREAD

**Issue by cvgaviao** [RepreZen/KaiZen-OpenAPI-Editor#485]
An OpenID Connect schema does require only two fields:

```
  securitySchemes:
    OpenIdC:  
      type: openIdConnect
      openIdConnectUrl: http://172.17.0.2:8080/.well-known/openid-configuration

```

Then in a Path we need to refer to a security schema using `security`tag:

```
      security:
        - OpenIdC: 
          - admin   <------ error issued here 

```

But editor is wrongly issuing an error as the schema were oAuth2: `"admin" does not match any scope name defined in the OpenIdC security scheme. `
